apiVersion: v1
items:
- apiVersion: apps.cloudfoundry.org/v1alpha1
  kind: RouteBulkSync
  metadata:
    annotations:
      kapp.k14s.io/change-rule.istio-sidecar-injector: upsert after upserting cf-for-k8s.cloudfoundry.org/istio-sidecar-injector
      kapp.k14s.io/identity: v1;cf-workloads/apps.cloudfoundry.org/RouteBulkSync/route-bulk-sync;apps.cloudfoundry.org/v1alpha1
      kapp.k14s.io/original: '{"apiVersion":"apps.cloudfoundry.org/v1alpha1","kind":"RouteBulkSync","metadata":{"annotations":{"kapp.k14s.io/change-rule.istio-sidecar-injector":"upsert
        after upserting cf-for-k8s.cloudfoundry.org/istio-sidecar-injector"},"labels":{"kapp.k14s.io/app":"1590385260149929678","kapp.k14s.io/association":"v1.b390afcdb9a327cf2015c669b22131f2","shalm.wonderix.github.com/app":"cf-for-k8s","shalm.wonderix.github.com/version":"0.0.0"},"name":"route-bulk-sync","namespace":"cf-workloads"},"spec":{"selector":{"matchLabels":{"cloudfoundry.org/route-bulk-sync":"true"}},"template":{"metadata":{"labels":{"cloudfoundry.org/route-bulk-sync":"true"}}}}}'
      kapp.k14s.io/original-diff: |
        []
      kapp.k14s.io/original-diff-full: ""
      kapp.k14s.io/original-diff-md5: 58e0494c51d30eb3494f7c9198986bb9
    creationTimestamp: "2020-05-25T05:41:20Z"
    generation: 1
    labels:
      kapp.k14s.io/app: "1590385260149929678"
      kapp.k14s.io/association: v1.b390afcdb9a327cf2015c669b22131f2
      shalm.wonderix.github.com/app: cf-for-k8s
      shalm.wonderix.github.com/version: 0.0.0
    name: route-bulk-sync
    namespace: cf-workloads
    resourceVersion: "3965"
    selfLink: /apis/apps.cloudfoundry.org/v1alpha1/namespaces/cf-workloads/routebulksyncs/route-bulk-sync
    uid: a6b890f7-3c80-4a81-9ea5-53a5f8c6c8fa
  spec:
    selector:
      matchLabels:
        cloudfoundry.org/route-bulk-sync: "true"
    template:
      metadata:
        labels:
          cloudfoundry.org/route-bulk-sync: "true"
  status:
    observedGeneration: 1
- apiVersion: networking.cloudfoundry.org/v1alpha1
  kind: Route
  metadata:
    creationTimestamp: "2020-05-25T09:26:05Z"
    generation: 2
    labels:
      app.kubernetes.io/component: cf-networking
      app.kubernetes.io/managed-by: cloudfoundry
      app.kubernetes.io/name: 25cf2d6c-7f27-4bbb-801e-043dfd5e406c
      app.kubernetes.io/part-of: cloudfoundry
      app.kubernetes.io/version: 0.0.0
      cloudfoundry.org/domain_guid: f11b0021-ebda-4186-9545-9d2fae988154
      cloudfoundry.org/org_guid: e9aab7d8-298f-4aa7-9a77-46a721a36197
      cloudfoundry.org/route_guid: 25cf2d6c-7f27-4bbb-801e-043dfd5e406c
      cloudfoundry.org/space_guid: e7bb5fa9-9496-4179-b244-806b268a8c64
    name: 25cf2d6c-7f27-4bbb-801e-043dfd5e406c
    namespace: cf-workloads
    resourceVersion: "49649"
    selfLink: /apis/networking.cloudfoundry.org/v1alpha1/namespaces/cf-workloads/routes/25cf2d6c-7f27-4bbb-801e-043dfd5e406c
    uid: 30aa8a50-0191-4fb2-b8f0-439eb558db37
  spec:
    destinations:
    - app:
        guid: 673ab4f3-101c-41a6-b1e3-aca13da1dd45
        process:
          type: web
      guid: 833a86e8-414f-4ac7-882b-6bc0c3c40366
      port: 8080
      selector:
        matchLabels:
          cloudfoundry.org/app_guid: 673ab4f3-101c-41a6-b1e3-aca13da1dd45
          cloudfoundry.org/process_type: web
    domain:
      internal: false
      name: cf.cf4k8s.istio.shoot.canary.k8s-hana.ondemand.com
    host: test-app-b
    path: ""
    url: test-app-b.cf.cf4k8s.istio.shoot.canary.k8s-hana.ondemand.com
- apiVersion: networking.cloudfoundry.org/v1alpha1
  kind: Route
  metadata:
    creationTimestamp: "2020-05-25T09:25:15Z"
    generation: 2
    labels:
      app.kubernetes.io/component: cf-networking
      app.kubernetes.io/managed-by: cloudfoundry
      app.kubernetes.io/name: 8aace289-6280-4bea-b35f-9ff0fdf6ebfb
      app.kubernetes.io/part-of: cloudfoundry
      app.kubernetes.io/version: 0.0.0
      cloudfoundry.org/domain_guid: f11b0021-ebda-4186-9545-9d2fae988154
      cloudfoundry.org/org_guid: 3fb71d09-ad79-4090-984c-cfa86f80ddb8
      cloudfoundry.org/route_guid: 8aace289-6280-4bea-b35f-9ff0fdf6ebfb
      cloudfoundry.org/space_guid: 9625cbad-8029-4cf2-9351-b70e3b53f8ec
    name: 8aace289-6280-4bea-b35f-9ff0fdf6ebfb
    namespace: cf-workloads
    resourceVersion: "49428"
    selfLink: /apis/networking.cloudfoundry.org/v1alpha1/namespaces/cf-workloads/routes/8aace289-6280-4bea-b35f-9ff0fdf6ebfb
    uid: 82038fc4-14f2-4889-8afc-15ac17818434
  spec:
    destinations:
    - app:
        guid: 292c7ae2-8d4c-449c-bd56-ec40ca644d57
        process:
          type: web
      guid: 7afcae7d-d2ff-4310-9e74-2ec9ca4cca19
      port: 8080
      selector:
        matchLabels:
          cloudfoundry.org/app_guid: 292c7ae2-8d4c-449c-bd56-ec40ca644d57
          cloudfoundry.org/process_type: web
    domain:
      internal: false
      name: cf.cf4k8s.istio.shoot.canary.k8s-hana.ondemand.com
    host: test-app-a
    path: ""
    url: test-app-a.cf.cf4k8s.istio.shoot.canary.k8s-hana.ondemand.com
- apiVersion: networking.cloudfoundry.org/v1alpha1
  kind: Route
  metadata:
    creationTimestamp: "2020-05-25T09:26:53Z"
    generation: 2
    labels:
      app.kubernetes.io/component: cf-networking
      app.kubernetes.io/managed-by: cloudfoundry
      app.kubernetes.io/name: 93a9af20-fdee-47ec-ba81-2df2c717b23a
      app.kubernetes.io/part-of: cloudfoundry
      app.kubernetes.io/version: 0.0.0
      cloudfoundry.org/domain_guid: f11b0021-ebda-4186-9545-9d2fae988154
      cloudfoundry.org/org_guid: e9aab7d8-298f-4aa7-9a77-46a721a36197
      cloudfoundry.org/route_guid: 93a9af20-fdee-47ec-ba81-2df2c717b23a
      cloudfoundry.org/space_guid: e7bb5fa9-9496-4179-b244-806b268a8c64
    name: 93a9af20-fdee-47ec-ba81-2df2c717b23a
    namespace: cf-workloads
    resourceVersion: "49863"
    selfLink: /apis/networking.cloudfoundry.org/v1alpha1/namespaces/cf-workloads/routes/93a9af20-fdee-47ec-ba81-2df2c717b23a
    uid: b06357d7-2c23-47da-a8f8-597d9bde181b
  spec:
    destinations:
    - app:
        guid: 673ab4f3-101c-41a6-b1e3-aca13da1dd45
        process:
          type: web
      guid: daad15e0-70b4-4dba-aab8-4c9f49304a6f
      port: 8080
      selector:
        matchLabels:
          cloudfoundry.org/app_guid: 673ab4f3-101c-41a6-b1e3-aca13da1dd45
          cloudfoundry.org/process_type: web
    domain:
      internal: false
      name: cf.cf4k8s.istio.shoot.canary.k8s-hana.ondemand.com
    host: test-app-b1
    path: ""
    url: test-app-b1.cf.cf4k8s.istio.shoot.canary.k8s-hana.ondemand.com
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
